name: "[Automação] Setup de repositório"
description: "Criação automatizada"
title: "Criação de repositórios"
labels: ["setup"]
assignees: 
  - ${{github.author}}
body:
  - type: markdown
    attributes:
      value: |
        Abaixo está alguns campos para você inciar sua aplicação!
  - type: input
    id: repository
    attributes:
      label: ">>repository<<"
      description: Nome do serviço ou aplicação?
    validations:
      required: true
  - type: dropdown
    id: template
    attributes:
      label: ">>template<<"
      description: Qual template você deseja?
      options:
        - genesis-template-node
        - genesis-template-infra
        - genesis-template-empty
    validations:
      required: true