name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  create-repository:
    runs-on: ubuntu-latest
    needs: [create-comment]
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Show parsed data JSON
        run: |
          echo "${{ steps.parse.outputs.payload }}"
          repository="$(echo "$output" | jq -r '.Repository')"
          template="$(echo "$output" | jq -r '.Template')"
          echo "Repository: $repository"
          echo "Template: $template"

  close-github-issue:
    runs-on: ubuntu-latest
    needs: create-repository
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue