name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]
  
jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  parse-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Body
        id: parse_body
        run: |
          function parseKeyValue(string) {
            const lines = string.split('\n');
            const result = {};
            lines.forEach((line) => {
              const [key, value] = line.split(': ');
              result[key] = value;
            });
            return result;
          }

          const body = parseKeyValue(github.event.issue.body);
          const { template, repository } = body;

          console.log(`template: ${template}`);
          console.log(`repository: ${repository}`);

  create-github-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository information
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
  
  close-github-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        uses: actions/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}