name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]
  
jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  parse-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Parse issue body
        uses: peter-murray/issue-body-parser-action@v1
        id: parse-body
        with:
          issue-number: ${{ github.event.issue.number }}

      - name: Create repository
        run: |
          REPOSITORY_NAME=${{ steps.parse-body.outputs.repository }}
          TEMPLATE=${{ steps.parse-body.outputs.template }}
          echo "Creating repository $REPOSITORY_NAME using template $TEMPLATE..."
          # Add commands to create the repository here

  create-github-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository information
        run: |
          echo "Repo Name: ${{ github.event.issue.body }}"
  
  close-github-issue:
    runs-on: ubuntu-latest
    needs: [create-github-repo, create-comment]
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue