name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  create-repository:
    runs-on: ubuntu-latest
    needs: [extract-content]
    steps:
      - name: Echo
        run: |
          echo ${{ needs.extract-content.outputs }}
  
  close-github-issue:
    runs-on: ubuntu-latest
    needs: [create-repository, create-comment]
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue