name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]
  
jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  create-github-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository information
        run: |
          echo "Repo Name: ${{ github.event.issue.body }}"
  
  close-github-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue