name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]
  
jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  parse-issue-body:
    runs-on: ubuntu-latest

    steps:
      - name: Parse issue body
        uses: peter-murray/issue-body-parser-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}
      - name: Display issue body
        run: |
          echo "${{ steps.parse_issue_body.outputs.repository }}"
          echo "${{ steps.parse_issue_body.outputs.template }}"

  create-github-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Getting repository information
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"