name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  create-repository:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [create-comment]
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Show parsed data JSON
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          echo "${{ steps.parse.outputs.payload }}"
          output="${{ steps.parse.outputs.payload }}"
          repository="$(echo $output | awk -F '[,:]' '{print $2}' | tr -d '{}')"
          template="$(echo $output | awk -F '[,:]' '{print $4}' | tr -d '{}')"
          echo "Repository: $repository"
          echo "Template: $template"
          gh repo new repo-test

  close-github-issue:
    runs-on: ubuntu-latest
    needs: create-repository
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue