name: Criação de Repositório Automatizado

on:
  issues:
    types: [opened, reopened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Criando repositório: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  create-repository:
    runs-on: ubuntu-latest
    needs: [create-comment]
    steps:
      - name: Restore outputs from cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: outputs
          key: ${{ runner.os }}-extract-content-${{ hashFiles('outputs/repository outputs/template') }}
      - name: Use extracted content
        if: steps.restore-cache.outputs.cache-hit == 'true'
        run: |
          repository="$(cat outputs/repository)"
          template="$(cat outputs/template)"
          echo "Repository: $repository"
          echo "Template: $template"

  close-github-issue:
    runs-on: ubuntu-latest
    needs: create-repository
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue